#!/usr/bin/env python3
"""Write assets/LICENSES.md from assets/manifest.json (audio) plus the fixed notes for icons and fonts."""
import json, os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    items = json.load(open(os.path.join(HERE, "assets", "manifest.json"), encoding="utf-8"))["assets"]
    out = ["# Asset licences", "",
           "Generated by `tools/make_licenses.py` from `assets/manifest.json`; the licence text of every piece was read at its source (see `license_evidence`).", "",
           "* Icons: Lucide (ISC), `assets/svg/LICENSE-lucide.txt`. Hand-drawn doodles are generated by `sketch.py` (this project).",
           "* Fonts: SIL Open Font License 1.1, one `OFL-*.txt` per family in `fonts/`.",
           "* Audio: below. CC0 needs no credit; CC-BY must be credited (the editor writes `<video>.credits.txt` on export).", ""]
    for kind, title in (("music", "Music"), ("sfx", "Sound effects")):
        out += [f"## {title}", "", "| id | title | author | licence | source |", "|---|---|---|---|---|"]
        for it in sorted((i for i in items if i["kind"] == kind), key=lambda i: (i["license"], i["id"])):
            out.append(f"| {it['id']} | {it['title']} | {it['author']} | {it['license']} | {it.get('page_url') or it['source_url']} |")
        out.append("")
    open(os.path.join(HERE, "assets", "LICENSES.md"), "w", encoding="utf-8").write("\n".join(out))
    print("assets/LICENSES.md:", len(items), "assets")


if __name__ == "__main__":
    main()
